name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.7
  - pyyaml
  # optional dependencies pulled in by pip install dask[bag, delayed]
  - cloudpickle
  - partd
  - fsspec
  - toolz
  # test dependencies
  - pytest
  - pytest-rerunfailures
  - pytest-xdist
