name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.7
  - pyyaml
  # optional dependencies pulled in by pip install dask[array, dataframe]
  - numpy=1.15.0
  - pandas=0.25.0
  - partd
  - fsspec
  - toolz
  # test dependencies
  - pytest
  - pytest-xdist
