name: testenv
channels:
  - conda-forge
dependencies:
  - zstandard
  - bokeh=1.4.0
  - click
  - cloudpickle
  - dask
  - dill
  - lz4
  - ipykernel
  - ipywidgets
  - joblib
  - jupyter_client
  - msgpack-python>=0.6.0
  - prometheus_client
  - psutil
  - pytest
  - requests
  - toolz
  - tblib
  - zict
  - fsspec
  - pip
  - pip:
      - pytest-repeat
      - pytest-timeout
      - pytest-faulthandler
      - sortedcollections
      - pytest-asyncio
      - git+https://github.com/dask/dask
      - git+https://github.com/joblib/joblib.git
      - git+https://github.com/dask/zict
