# This job includes coverage
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.7
  - packaging
  - numpy=1.18
  - pandas=1.0
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - moto
  - flask
  - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  - xarray
  - fsspec
  # sqlalchemy 1.4.0 causes deprecation warnings to be raised from pandas
  # along with other issues https://github.com/pandas-dev/pandas/issues/40467
  - sqlalchemy<1.4.0
  - pyarrow=1.0
  - coverage
  - jsonschema
  # other -- IO
  - bcolz
  - blosc
  - boto3
  - botocore
  - aiohttp
  - bokeh
  - httpretty
  - chest
  - s3fs
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz
  - ipython
  - lz4
  - numba
  - partd
  - pickle5
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - pandas-datareader
  - python-xxhash
  - mmh3
  - jinja2
  - pip
  - pip:
    - git+https://github.com/dask/distributed
