# This job includes coverage
name: test-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required dependencies
  - python=3.9
  - setuptools<60.0
  - packaging
  - numpy
  - pandas
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - moto
  - flask
  - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  # resolver was pulling in old versions, so hard-coding floor
  # https://github.com/dask/dask/pull/8505
  - tiledb>=2.5.0
  - xarray
  - fsspec
  - sqlalchemy>=1.4.0
  - pyarrow
  - coverage<6.3 # https://github.com/nedbat/coveragepy/issues/1310
  - jsonschema
  # other -- IO
  # Not available for Python 3.9 on conda-forge
  # - bcolz
  - blosc
  - boto3
  - botocore
  - bokeh
  - httpretty
  - aiohttp
  # Need recent version of s3fs to support newer aiobotocore versions
  # https://github.com/dask/s3fs/issues/514
  - s3fs>=2021.8.0
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - ipython
  - lz4
  - numba
  - partd
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy<1.8.0 # See https://github.com/dask/dask/issues/8682
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - python-xxhash
  - mmh3
  - jinja2
  - pip
  - pip:
    # TODO: Switch back to main when ToPickle is merged
    # - git+https://github.com/dask/distributed
    - git+https://github.com/madsbk/distributed/tree/to_pickle
