name: dask-distributed
channels:
  - conda-forge
  - defaults
dependencies:
  - zstandard
  - bokeh!=2.0.0
  - click
  - cloudpickle
  - dask
  - lz4
  - ipykernel
  - ipywidgets
  - joblib
  - jupyter_client
  - msgpack-python>=0.6.0
  - prometheus_client
  - psutil
  - pytest
  - pytest-asyncio
  - pytest-repeat
  - pytest-timeout
  - pytest-faulthandler
  - requests
  - sortedcollections
  - toolz
  - tblib
  - zict
  - fsspec
  - pip
  - pip:
      - git+https://github.com/dask/dask
      - git+https://github.com/joblib/joblib.git
      - git+https://github.com/dask/zict
