# This job includes coverage
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.7
  - numpy=1.15
  - pandas=0.25
  # test dependencies
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
  - moto
  - flask
  # Issue with conda package for NumPy 1.15
  # See fastparquet-444
  # - fastparquet
  - h5py
  - pytables
  - zarr
  - tiledb-py
  - xarray
  - fsspec
  - sqlalchemy
  - pyarrow=0.14
  - coverage
  - jsonschema
  # other -- IO
  - bcolz
  - blosc
  - boto3
  - botocore
  - aiohttp
  - bokeh
  - httpretty
  - chest
  - s3fs
  - cloudpickle
  - crick
  - cytoolz
  - distributed
  - graphviz
  - ipython
  - lz4
  - numba
  - partd
  - pickle5
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - toolz
  - python-snappy
  - sparse
  - cachey
  - python-graphviz
  - pandas-datareader
  - python-xxhash
  - mmh3
  - pip
  - pip:
    - git+https://github.com/dask/distributed
