name: Additional

on: [push, pull_request]

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  mindeps:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        environment: ["mindeps-array", "mindeps-dataframe", "mindeps-non-optional", "mindeps-distributed"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.2.0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: "3.8"
          environment-file: continuous_integration/environment-${{ matrix.environment }}.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        run: source continuous_integration/scripts/run_tests.sh

  doctest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.2.0

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: "3.10"
          environment-file: continuous_integration/environment-3.10.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Install
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        run: pytest -v --doctest-modules --ignore-glob='*/test_*.py' dask

  imports:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.2.0

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          python-version: "3.8"
          activate-environment: test-environment
          auto-activate-base: false

      - name: Run import tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: source continuous_integration/scripts/test_imports.sh
