name: Windows CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: continuous_integration/environment.yml
          activate-environment: testenv
          auto-activate-base: false

      - name: Install tornado
        shell: bash -l {0}
        run: |
          if [[ "${{ matrix.python-version }}" = "3.8" ]]; then
            conda install -c conda-forge tornado=6
          else
            conda install -c conda-forge tornado=5
          fi

      - name: List packages in environment
        shell: bash -l {0}
        run: conda list

      - name: Install distributed from source
        shell: bash -l {0}
        run: python -m pip install -q --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        env:
          PYTHONFAULTHANDLER: 1
        run: py.test -m "not avoid_travis" distributed -r s --timeout-method=thread --timeout=300 --durations=20
