name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  checks:
    name: Documentation build
    runs-on: ubuntu-latest
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    #- name: Checkout
      #uses: actions/checkout@v2

    #- name: Set up Python 3.7
      #uses: actions/setup-python@v1
      #with:
        #python-version: 3.7

    #- name: Install Dask
      #run: |
        #python -m pip install --upgrade pip
        #python -m pip install -e .

    #- name: Install doc dependencies
      #run: python -m pip install -r docs/requirements-docs.txt

    #- name: Build docs
      #run: |
        #cd docs
        #make html
