name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6,18 * * *"

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.environment }}${{ matrix.array-expr == 'true' && ' / array-expr' || matrix.extra && format(' / {0}', matrix.extra) || '' }} Run ${{ matrix.run }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        # Note: after adding/removing builds here, update
        # codecov.yml to match.
        os: [ubuntu-latest]
        environment: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t", "mindeps-dataframe"]
        extra: [null]
        array-expr: ["false"]
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Needed by codecov.io

      - name: Setup Java
        uses: actions/setup-java@v5
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3.3.0
        with:
          miniforge-version: latest
          use-mamba: true
          channel-priority: strict
          environment-file: continuous_integration/environment-${{ matrix.environment }}.yaml
          activate-environment: test-environment
          auto-activate-base: false
          run-post: ${{ matrix.os != 'windows-latest' }}

      - name: Test pandas nightlies (only with dask-expr)
        if: ${{ matrix.extra == 'pandas-nightly' }}
        run: python -m pip install --pre --extra-index https://pypi.anaconda.org/scientific-python-nightly-wheels/simple pandas -U

      - name: Disable auto pyarrow strings for 3.10 builds
        if: ${{ matrix.environment == '3.10' }}
        run: |
          export DASK_DATAFRAME__CONVERT_STRING="False"
          echo "DASK_DATAFRAME__CONVERT_STRING: $DASK_DATAFRAME__CONVERT_STRING"
          echo "DASK_DATAFRAME__CONVERT_STRING=$DASK_DATAFRAME__CONVERT_STRING" >> $GITHUB_ENV

      # FIXME https://github.com/msgpack/msgpack-python/issues/613
      - name: Disable msgpack C extension on free-threading
        if: ${{ matrix.environment == '3.14t' }}
        run: |
          conda uninstall -y -v --force msgpack-python
          MSGPACK_PUREPYTHON=1 pip install msgpack --no-binary msgpack --no-cache --force-reinstall -v
          python -Werror -c 'import msgpack'

      - name: Reconfigure pytest-timeout
        # No SIGALRM available on Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: sed -i.bak 's/timeout_method = "thread"/timeout_method = "signal"/' pyproject.toml

      - name: Install
        run: source continuous_integration/scripts/install.sh

      - name: Enable Array Expr
        if: ${{ matrix.array-expr == 'true' }}
        run: |
          export DASK_ARRAY__QUERY_PLANNING="True"
          echo "DASK_ARRAY__QUERY_PLANNING: $DASK_ARRAY__QUERY_PLANNING"
          echo "DASK_ARRAY__QUERY_PLANNING=$DASK_ARRAY__QUERY_PLANNING" >> $GITHUB_ENV

      - name: Run import tests
        run: pytest dask/tests/test_imports.py

      - name: Run tests
        id: run_tests
        env:
          PARALLEL: "false"
          COVERAGE: "false"
          ARRAYEXPR: ${{ matrix.array-expr }}
          HDF5_USE_FILE_LOCKING: "FALSE"
        run: source continuous_integration/scripts/run_tests.sh
