name: Check for gpuCI updates

on:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch:

jobs:
  update-gpuci:
    runs-on: ubuntu-latest
    if: github.repository == 'dask/dask'

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Parse current axis YAML
        id: rapids_current
        uses: the-coding-turtle/ga-yaml-parser@v0.1.2
        with:
          file: continuous_integration/gpuci/axis.yaml

      - name: Get latest cuDF nightly version
        id: cudf_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "cudf"
          version_system: "CalVer"

      - name: Get latest UCX-Py nightly version
        id: ucx_py_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "ucx-py"
          version_system: "CalVer"

      - name: Get old RAPIDS / UCX-Py versions
        env:
          FULL_RAPIDS_VER: ${{ steps.cudf_latest.outputs.version }}
          FULL_UCX_PY_VER: ${{ steps.ucx_py_latest.outputs.version }}
        run: |
          echo RAPIDS_VER=${{ steps.rapids_current.outputs.RAPIDS_VER_0 }} >> $GITHUB_ENV
          echo UCX_PY_VER=$(curl -sL https://version.gpuci.io/rapids/${{ steps.rapids_current.outputs.RAPIDS_VER_0 }}) >> $GITHUB_ENV
          echo NEW_RAPIDS_VER=$(echo $FULL_RAPIDS_VER | cut -d'.' -f1,2) >> $GITHUB_ENV
          echo NEW_UCX_PY_VER=$(echo $FULL_UCX_PY_VER | cut -d'.' -f1,2) >> $GITHUB_ENV

      - name: Update RAPIDS version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'continuous_integration\/gpuci\/axis\.yaml'
          find: "${{ env.RAPIDS_VER }}"
          replace: "${{ env.NEW_RAPIDS_VER }}"
          regex: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        if: ${{ env.UCX_PY_VER != env.NEW_UCX_PY_VER }}  # make sure new ucx-py nightlies are available
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          commit-message: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_RAPIDS_VER }}`"
          title: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_RAPIDS_VER }}`"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "upgrade-gpuci-rapids"
          body: |
            New cuDF and ucx-py nightly versions have been detected.

            Updated `axis.yaml` to use `${{ env.NEW_RAPIDS_VER }}`.
